TourOperator/Models/Booking.cs
using System.Diagnostics.CodeAnalysis;

namespace TourOperator.Models;

public class Booking
{
    public int Id { get; set; }
    public string Username { get; set; }
    public int RoomId { get; set; }
    public int TourId { get; set; }
    public DateTime DateBooked { get; set; }
    public DateTime DateFrom { get; set; }
    public DateTime DateTo { get; set; }
    public int TotalCost { get; set; }
    public bool DepositPaid { get; set; }
    public int Due { get; set; }
}

TourOperator/Controllers/AuthController.cs
namespace TourOperator.Controllers;

using System.Security.Claims;
using Contexts;
using Extensions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models.Entities;

[Controller]
[Route("/auth")]
public class AuthController : Controller
{
    private readonly ILogger<ViewController> _logger;
    private readonly TourDbContext _tourDbContext;

    public AuthController(TourDbContext tourDbContext, ILogger<ViewController> logger)
    {
        _tourDbContext = tourDbContext;
        _logger = logger;
    }

    /// <summary>
    /// Logs out the user by deleting their cookie from the browser.
    /// </summary>
    [HttpGet("logout")]
    [Authorize]
    public async Task<ActionResult> Logout()
    {
        _logger.LogInformation("User {} logged out.", User.Identity.Name);

        await HttpContext.SignOutAsync(
        CookieAuthenticationDefaults.AuthenticationScheme);

        return Redirect("/");
    }
    
    /// <summary>
    /// GET handler for the login page
    /// </summary>
    /// <returns>Login page view</returns>
    [HttpGet("login")]
    public IActionResult Login()
    {
        return View();
    }

    /// <summary>
    /// POST handler for login endpoint.
    /// Authenticates user, then if username and password correct gives the user a cookie with their
    /// claims, inc. roles extracted from the database.
    /// </summary>
    /// <param name="username">Username as string</param>
    /// <param name="password">Password as string</param>
    /// <returns>Success: Redirect to home page. Failure: Invalid password message.</returns>
    [HttpPost("login")]
    public async Task<ActionResult> Login([FromForm] string username, [FromForm] string password)
    {
        Customer? existing = _tourDbContext.Customers
            .Include(c => c.Role)
            .SingleOrDefault(c => c.Username == username);

        // Username not found
        if (existing == null)
            goto INVALID_PASSWORD;

        string attemptHash = password.Sha256();

        // Password incorrect
        if (existing.Password != attemptHash)
            goto INVALID_PASSWORD;

        // User claims of name and role can be accessed from the asp.net `User` object
        var claims = new List<Claim>
        {
            new Claim(ClaimTypes.Name, existing.Username),
            new Claim(ClaimTypes.Role, existing.Role.Name),
        };

        var claimsIdentity = new ClaimsIdentity(
            claims, CookieAuthenticationDefaults.AuthenticationScheme);

        var authProperties = new AuthenticationProperties
        {
            
        };
        
        // Give the user an authentication cookie.
        await HttpContext.SignInAsync(
            CookieAuthenticationDefaults.AuthenticationScheme, 
            new ClaimsPrincipal(claimsIdentity), 
            authProperties
        );
        
        _logger.LogInformation("User {} logged in.", existing.Username);
        
        return Redirect("/");
        
        // Common invalid password handler. Common handlers are the only useful application of GOTO, especially
        // here where the usage is explicitly clear.
INVALID_PASSWORD:
        _logger.LogInformation("Failed login, User {}.", username);
        return Problem("Invalid username or password");
    }
    
    /// <summary>
    /// GET handler for register page
    /// </summary>
    /// <returns>Register page with a new, blank customer object</returns>
    [HttpGet("register")]
    public IActionResult Register()
    {
        return View(new Customer());
    }
    
    /// <summary>
    /// POST handler for register page
    /// </summary>
    /// <param name="customer">Customer object with all fields but role filled in</param>
    /// <returns>Success: redirect to home page. Failure: redirect back to register page with errors shown.</returns>
    [HttpPost("register")]
    public ActionResult<Customer> Register([FromForm] Customer customer)
    {
        ModelState.Remove(ModelState.Keys.First(key => key == "Role"));
        
        // If all model validations successful
        if (ModelState.IsValid) {
            // Extract role object of customer
            customer.Role = _tourDbContext.Roles
                .Where(r => r.Name == RoleName.Customer)
                .SingleOrDefault();
            
            customer.Password = customer.Password.Sha256();

            // Add the customer object to the db
            _tourDbContext.Customers.Add(customer);
            _tourDbContext.SaveChanges();

            _logger.LogInformation("User {} created.", customer.Username);

            // TODO: Log in the user
            Customer? createdCustomer = _tourDbContext.Customers.Find(customer.Id);

            if (createdCustomer != null)
                return Redirect("/");
            
            return Problem("Failed to create customer");
        }
        
        // Log all errors to server console
        ModelState.Select(x => x.Value.Errors)
            .Where(y=>y.Count>0)
            .ToList()
            .ForEach(error => {
                _logger.LogError("Registration validation error: {0}", error.Select(x => x.ErrorMessage));
            });

        return View(customer);
    }


    /// <summary>
    /// Add a room to the package, using the session cookie.
    /// </summary>
    /// <param name="roomId">Id of the room to add</param>
    /// <param name="fromDate">Start date as yyyy-mm-dd</param>
    /// <param name="toDate">End date as yyyy-mm-dd</param>
    /// <returns>Success: Redirect to the page of the room hotel. Failure: Error message when room id invalid</returns>
    [HttpPost("room/addToPackage")]
    [Authorize]
    public ActionResult AddRoomToPackage([FromForm] int roomId, [FromForm] string fromDate, [FromForm] string toDate)
    {
        Room? room = _tourDbContext.Rooms.Find(roomId);
        
        if (room == null)
            return Problem($"Could not find room {roomId}");

        // Set the cookies
        HttpContext.Session.SetObject("PackageRoom", room);
        HttpContext.Session.SetObject("RoomDateTo", toDate.ParseDate());
        HttpContext.Session.SetObject("DateFrom", fromDate.ParseDate());
        
        return Redirect($"/Hotel/{room.HotelId}?fromDate={fromDate}&toDate={toDate}");
    }
    
    /// <summary>
    /// Add a tour to the package, using the session cookie.
    /// </summary>
    /// <param name="tourId">Id of the tour to add</param>
    /// <param name="fromDate">Start date as yyyy-mm-dd</param>
    /// <returns>Success: Redirect to the page of the tour. Failure: Error message when tour id invalid</returns>
    [HttpPost("tour/addToPackage")]
    [Authorize]
    public ActionResult AddTourToPackage([FromForm] int tourId, [FromForm] string fromDate)
    {
        Tour? tour = _tourDbContext.Tours.Find(tourId);
        
        if (tour == null)
            return Problem($"Could not find tour {tourId}");
        
        // Set the cookies
        HttpContext.Session.SetObject("PackageTour", tour);
        HttpContext.Session.SetObject("DateFrom", fromDate.ParseDate());
        
        return Redirect($"/Tour/{tour.Id}?fromDate={fromDate}");
    }
}

TourOperator/Controllers/BookingController.cs
namespace TourOperator.Controllers;

using Contexts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models.Entities;
using Models.Services;

[Controller]
[Route("/booking")]
public class BookingController : Controller
{
    private readonly ILogger<ViewController> _logger;
    private readonly TourDbContext _tourDbContext;
    private readonly AvailabilityService _availabilitySvc;


    public BookingController(TourDbContext tourDbContext, ILogger<ViewController> logger)
    {
        _tourDbContext = tourDbContext;
        _logger = logger;
        _availabilitySvc = new AvailabilityService(_tourDbContext);
    }

    /// <summary>
    /// Make the 20% deposit to reserve a booking
    /// </summary>
    /// <param name="booking">Booking object to make deposit for</param>
    /// <returns>Redirect to the booking information page</returns>
    [HttpPost("deposit")]
    [Authorize]
    public ActionResult<Booking> MakeDeposit([FromForm] Booking booking)
    {
        // Set the booking information, set the due amount.
        booking.DepositPaid = true;
        booking.Customer = _tourDbContext.Customers.Single(c => c.Id == booking.CustomerId);
        booking.Due = (int) (booking.TotalCost * 0.8);
        booking.DateBooked = DateTime.Now;

        // Add to database bookings table.
        _tourDbContext.Bookings.Add(booking);
        _tourDbContext.SaveChanges();
        
        return Redirect($"/booking?bookingId={booking.Id}");
    }
    
   
    /// <summary>
    /// Confirm a booking by paying the full amount
    /// </summary>
    /// <param name="bookingId">Id of the booking to confirm</param>
    /// <returns>Success: redirect to the booking info page. Failure: Error message when bookingId is invalid</returns>
    [HttpGet("confirm")]
    [Authorize]
    public ActionResult<Booking> ConfirmBooking([FromQuery] int bookingId)
    {
        Booking? booking = _tourDbContext.Bookings
            .Include(b => b.Customer)
            .SingleOrDefault(b => b.Id == bookingId);

        if (booking == null)
            return Problem($"Cannot find booking {bookingId}");
        
        // Don't show bookings from other users.
        if(booking.Customer!.Username != User.Identity!.Name)
            return Problem($"Cannot load booking not for user {User.Identity!.Name}");

        // All due paid off
        booking.Due = 0;
        
        // Save changes in db
        _tourDbContext.Bookings.Update(booking);
        _tourDbContext.SaveChanges();
        
        return Redirect($"/booking?bookingId={booking.Id}");
    }
    
    /// <summary>
    /// Get current authenticated customer using User.Identity.Name from authentication cookie.
    /// </summary>
    /// <returns>Authenticated customer</returns>
    /// <exception cref="Exception">No user logged in.</exception>
    private Customer CurrentCustomer()
    {
        Customer customer = _tourDbContext.Customers
            .Where(c => c.Username == User.Identity!.Name)
            .FirstOrDefault() ;

        if (customer != null)
            return customer;

        throw new Exception("Invalid User");
    }
    
    /// <summary>
    /// GET handler for all customer bookings.
    /// </summary>
    /// <returns>Bookings page with list of all customer bookings.</returns>
    [HttpGet("all")]
    [Authorize]
    public ActionResult AllBookings()
    {
        int customerId = CurrentCustomer().Id;
        
        IEnumerable<Booking> bookings = _tourDbContext.Bookings
            .Include(b => b.RoomBooking!.Room!.Hotel)
            .Include(b => b.TourBooking!.Tour)
            .Where(b => b.CustomerId == customerId);

        return View(bookings);
    }
    
    /// <summary>
    /// GET handler for booking info page.
    /// </summary>
    /// <param name="bookingId">Id of the booking to examine</param>
    /// <returns>Success: booking info page. Failure: 500 error with message.</returns>
    [HttpGet]
    [Authorize]
    public IActionResult BookingInfo([FromQuery] int bookingId)
    {
        // Load booking, including all relevant fields such as Room, Tour, Hotel.
        Booking? booking = _tourDbContext.Bookings
            .Include(b => b.Customer)
            .Include(b => b.RoomBooking!.Room)
                .ThenInclude(r => r!.Hotel)
            .Include(b => b.TourBooking!.Tour)
            .FirstOrDefault(b => b.Id == bookingId);

        if (booking == null)
            return Problem($"Cannot find booking {bookingId}");
        
        // Don't show bookings from other users.
        if(booking.Customer!.Username != User.Identity!.Name)
            return Problem($"Cannot load booking not for user {User.Identity!.Name}");
        
        return View(booking);
    }
    
    /// <summary>
    /// GET handler for booking edit page.
    /// </summary>
    /// <param name="bookingId">Id of booking to edit</param>
    /// <returns>Success: booking edit page. Failure: Error when booking not found.</returns>
    [HttpGet("edit")]
    [Authorize]
    public ActionResult<Booking> EditBooking([FromQuery] int bookingId)
    {
        Booking? booking = _tourDbContext.Bookings
            .Include(b => b.RoomBooking)
            .Include(b => b.TourBooking)
            .SingleOrDefault(b => b.Id == bookingId);

        if (booking == null)
            return Problem($"Cannot find booking {bookingId}");
        
        return View(booking);
    }
    
    /// <summary>
    /// POST handler to check if a new booking date is available.
    /// </summary>
    /// <param name="bookingId">Id of booking to check</param>
    /// <param name="from">New start date</param>
    /// <returns>Success: availability of room and tour from that date. Failure: error when booking id invalid.</returns>
    [HttpPost("edit")]
    [Authorize]
    public ActionResult<Booking> CheckEditBooking([FromForm] int bookingId, [FromForm] DateTime from)
    {
        // Extract existing booking from database
        Booking? booking = _tourDbContext.Bookings
            .Include(b => b.RoomBooking)
                .ThenInclude(rb => rb.Room)
                    .ThenInclude(r => r.Hotel)
            .Include(b => b.TourBooking)
                .ThenInclude(tb => tb.Tour)
            .SingleOrDefault(b => b.Id == bookingId);

        if (booking == null)
            return Problem($"Cannot find booking {bookingId}");

        string error = "";
        
        if (booking.HasRoom()) {
            // Check room availability on that date.
            int days = (booking.RoomBooking!.DateTo - booking.RoomBooking!.DateFrom).Days;
            DateTime newTo = from.AddDays(days);
            
            IEnumerable<Room> rooms = _availabilitySvc
                .RoomsBetweenDates(booking.RoomBooking!.Room!.Hotel, from, newTo)
                .Where(r => r.Id == booking.RoomBooking!.Room!.Id);

            if (rooms.Any()) {
                // Update RoomBooking dates as valid.
                booking.RoomBooking.DateFrom = from;
                booking.RoomBooking.DateTo = newTo;
            }
            else {
                // Set error display message for view
                error = "Room unavailable";
            }
        }

        if (booking.HasTour()) {
            IEnumerable<Tour> tours = _availabilitySvc
                .ToursBetweenDates(from)
                .Where(t => t.Id == booking.TourBooking!.Tour!.Id);

            if (tours.Any()) {
                // Update TourBooking dates as valid.
                booking.TourBooking!.DateFrom = from;
            }
            else {
                // Set error display message for view
                error = "Tour unavailable";
            }
        }

        if (booking.GetDaysUntilStart() <= 14){
            // Add 5% surcharge for changing booking under 14 days from departure.
            booking.Due += (int) (booking.TotalCost * 0.05f);
        }

        // Pass errormsg to the view
        TempData["errormsg"] = error;
        
        return View("EditBooking", booking);
    }
    
    /// <summary>
    /// POST handler to confirm the editing of the booking
    /// </summary>
    /// <param name="bookingId">Id of the booking to update</param>
    /// <param name="from">New start date</param>
    /// <returns>Success: redirect to booking info page. Failure: 500 error with problem</returns>
    [HttpPost("update")]
    [Authorize]
    public ActionResult<Booking> ConfirmEditBooking([FromForm] int bookingId, [FromForm] DateTime from)
    {
        Booking? booking = _tourDbContext.Bookings
            .Include(b => b.RoomBooking)
            .ThenInclude(rb => rb.Room)
            .ThenInclude(r => r.Hotel)
            .Include(b => b.TourBooking)
            .ThenInclude(tb => tb.Tour)
            .SingleOrDefault(b => b.Id == bookingId);

        if (booking == null)
            return Problem($"Cannot find booking {bookingId}");

        // Do the same checking as `CheckBookingAvailability` to ensure places have not since been taken.
        
        if (booking.HasRoom()){
            int days = (booking.RoomBooking!.DateTo - booking.RoomBooking!.DateFrom).Days;
            DateTime newTo = from.AddDays(days);
            
            IEnumerable<Room> rooms = _availabilitySvc
                .RoomsBetweenDates(booking.RoomBooking!.Room!.Hotel, from, newTo)
                .Where(r => r.Id == booking.RoomBooking!.Room!.Id);

            if (rooms.Any()) {
                booking.RoomBooking.DateFrom = from;
                booking.RoomBooking.DateTo = newTo;
            }
            else {
                return Problem("Room unavailable");
            }
        }

        if (booking.HasTour()){
            IEnumerable<Tour> tours = _availabilitySvc
                .ToursBetweenDates(from)
                .Where(t => t.Id == booking.TourBooking!.Tour!.Id);

            if (tours.Any()){

TourOperator/Views/View/BookingConfirmed.cshtml
@using TourOperator.Extensions
@model TourOperator.Models.Entities.Booking

@{
    ViewData["Title"] = "Booking Confirmed";
}

<div class="text-center">
    <h1 class="display-4">Booking Confirmed!</h1>
    
    <h2>
        We hope you enjoy your trip!
    </h2>
    
    <div class="checkout">
    
        <table>
            <tr>
                <th>Type</th>
                <th>Name</th>
                <th>Cost</th>
                <th>Dates</th>
            </tr>
            
            <tr>
                <td>Hotel Room</td>
                <td>@Model.RoomBooking?.Room?.Name</td>
                <td>£@((Model.RoomBooking?.Room?.Price*Model.RoomBooking?.DateTo.Subtract(Model.RoomBooking.DateFrom).Days)/100)</td>
                <td>@Model.RoomBooking?.DateFrom.ToShortDate() To @Model.RoomBooking?.DateTo.ToShortDate()</td>
            </tr>
            
            <tr>
                <td>Tour</td>
                <td>@Model.TourBooking?.Tour?.Name</td>
                <td>£@(Model.TourBooking?.Tour?.Price/100)</td>
                <td>@Model.TourBooking?.DateFrom.ToShortDate() (@Model.TourBooking?.Tour?.Length Days)</td>
            </tr>
            
            <tr id="checkout-total">
                <td>Total</td>
                @if (Model.RoomBooking!.Room != null && Model.TourBooking!.Tour != null)
                {
                    <td>Package Discount (@(Model.RoomBooking!.Room.PackageDiscount)%)</td>
                }
                else
                {
                    <td></td>
                }
                <td>£@(Model.TotalCost / 100)</td>
                <td></td>
            </tr>
        </table>
    </div>
</div>

TourOperator/Views/View/BookingInfo.cshtml
@using TourOperator.Extensions
@model TourOperator.Models.Entities.Booking

@{
    ViewData["Title"] = "Booking Confirmed";
}

<div class="text-center">
    <h1 class="display-4">Booking Confirmed!</h1>
    
    <h2>
        We hope you enjoy your trip!
    </h2>
    
    <div class="checkout">
    
        <table>
            <tr>
                <th>Type</th>
                <th>Name</th>
                <th>Cost</th>
                <th>Dates</th>
            </tr>
            
            @if (Model.RoomBooking != null)
            {
                <tr>
                    <td>Hotel Room</td>
                    <td>@Model.RoomBooking?.Room?.Name</td>
                    <td>£@((Model.RoomBooking?.Room?.Price * Model.RoomBooking?.DateTo.Subtract(Model.RoomBooking.DateFrom).Days) / 100)</td>
                    <td>@Model.RoomBooking?.DateFrom.ToShortDate() To @Model.RoomBooking?.DateTo.ToShortDate()</td>
                </tr>
            }

            @if (Model.TourBooking != null)
            {
                <tr>
                    <td>Tour</td>
                    <td>@Model.TourBooking?.Tour?.Name</td>
                    <td>£@(Model.TourBooking?.Tour?.Price / 100)</td>
                    <td>@Model.TourBooking?.DateFrom.ToShortDate() (@Model.TourBooking?.Tour?.Length Days)</td>
                </tr>
            }
            
            <tr>
                <td>Deposit Paid</td>
                <td></td>
                <td>£@(Model.TotalCost*0.2 / 100)</td>
                <td></td>
            </tr>
            
            <tr>
                <td>Total</td>
                @if (Model.RoomBooking != null && Model.TourBooking != null)
                {
                    <td>Package Discount (@(Model.RoomBooking?.Room?.PackageDiscount)%)</td>
                }
                else
                {
                    <td></td>
                }
                <td>£@(Model.TotalCost / 100)</td>
                <td></td>
            </tr>

            <tr id="checkout-total">
                <td>Due</td>
                <td></td>
                <td>£@(Model.Due / 100)</td>
                <td></td>
            </tr>
        </table>
        
        @if (Model.Cancelled){
            <h3>You cancelled this order and have been refunded the total cost.</h3>
        }
        else{
            if (Model.IsForfeit()){
                <h3>Unfortunately, as you have not paid in 28 days, your booking has been forfeit.</h3>
            }

            if (!Model.IsForfeit()){
                <a class="btn btn-primary" asp-controller="View" asp-action="EditBooking" asp-route-bookingId="@Model.Id">
                    Edit Booking
                </a>

                if (Model.IsConfirmed()){
                    <a class="btn btn-danger" asp-controller="View" asp-action="CancelBooking" asp-route-bookingId="@Model.Id">
                        Cancel Booking
                    </a>
                }
            }

            if (!Model.IsConfirmed() && !Model.IsForfeit()){
                <h3> Pay by: @Model.StartDate().AddDays(-28).ToShortDate() </h3>

                <a class="btn btn-primary" asp-controller="Auth" asp-action="ConfirmBooking" asp-route-bookingId="@Model.Id">
                    Pay and Confirm
                </a>
            }
        }
    </div>
</div>

TourOperator/Views/View/CancelBooking.cshtml
@using TourOperator.Extensions
@model TourOperator.Models.Entities.Booking

@{
    ViewData["Title"] = "Cancel Booking?";
}

<div class="text-center">
    <h1 class="display-4">Cancel Booking?</h1>
    
    <h2>
        Are you sure?
    </h2>
    
    <p>You are cancelling your trip starting @Model.StartDate().ToShortDate()</p>
    
    @if (Model.GetDaysUntilStart() <= 5){
        <p class="error">You will have to pay a £50 administrative charge to cancel as you are due to depart in less than 5 days.</p>
    }
    
    @using (Html.BeginForm("ConfirmCancelBooking", "View", FormMethod.Post))
    {
        <input hidden="" name="bookingId" value="@Model.Id"/>
        
        <button type="submit" class="btn btn-danger">Cancel</button>
    }
</div>

TourOperator/Views/View/Checkout.cshtml
@using TourOperator.Extensions
@model TourOperator.Models.Entities.Booking

@{
    ViewData["Title"] = "Checkout";
}

<div class="text-center">
    <h1 class="display-4">Checkout</h1>
    
    <div class="checkout">
    
        <table>
            <tr>
                <th>Type</th>
                <th>Name</th>
                <th>Cost</th>
                <th>Dates</th>
            </tr>
            
            @if (Model.HasRoom())
            {
                <tr>
                    <td>Hotel Room</td>
                    <td>@Model.RoomBooking?.Room?.Name</td>
                    <td>£@(Model.RoomBooking?.Room?.Price * Model.RoomBooking?.DateTo.Subtract(Model.RoomBooking.DateFrom).Days / 100)</td>
                    <td>@Model.RoomBooking?.DateFrom.ToShortDate() To @Model.RoomBooking?.DateTo.ToShortDate()</td>
                </tr>
            }

            @if (Model.HasTour()) {
                <tr>
                    <td>Tour</td>
                    <td>@Model.TourBooking?.Tour?.Name</td>
                    <td>£@(Model.TourBooking?.Tour?.Price/100)</td>
                    <td>@Model.TourBooking?.DateFrom.ToShortDate() (@Model.TourBooking?.Tour?.Length Days)</td>
                </tr>
            }
            
            <tr id="checkout-total">
                <td>Total</td>
                @if (Model.HasRoom() && Model.HasTour())
                {
                    <td>Package Discount (@(Model.RoomBooking!.Room.PackageDiscount)%)</td>
                }
                else
                {
                    <td></td>
                }
                <td>£@(Model.TotalCost / 100)</td>
                <td></td>
            </tr>
        </table>
        
        @if (Model.TotalCost != 0){
            <h2>Deposit to be paid now: £@(Model.TotalCost * 0.2 / 100)</h2>

            @using (Html.BeginForm("MakeDeposit", "Booking", FormMethod.Post)){
                @Html.HiddenFor(model => model.CustomerId)
                @Html.HiddenFor(model => model.Customer)
        
                if (Model.HasRoom()){
                    @Html.HiddenFor(model => model.RoomBooking)
                    @Html.HiddenFor(model => model.RoomBooking!.RoomId)
                    @Html.HiddenFor(model => model.RoomBooking!.DateFrom)
                    @Html.HiddenFor(model => model.RoomBooking!.DateTo)
                }

                if (Model.HasTour()){
                    @Html.HiddenFor(model => model.TourBooking!.TourId)
                    @Html.HiddenFor(model => model.TourBooking!.DateFrom)
                    @Html.HiddenFor(model => model.TourBooking)
                }
                
                @Html.HiddenFor(model => model.DateBooked)
                @Html.HiddenFor(model => model.TotalCost)
                @Html.HiddenFor(model => model.DepositPaid)
                @Html.HiddenFor(model => model.Due)

                <button type="submit" class="btn btn-primary">Make Deposit</button>
            }
        }

    </div>
</div>

TourOperator/Views/View/Hotel.cshtml
@using TourOperator.Extensions
@using TourOperator.Models.Entities
@model TourOperator.Models.Entities.Hotel

@{
    ViewData["Title"] = "Hotels";
    string fromDate = ViewBag.Message["fromDate"];
    string toDate = ViewBag.Message["toDate"];
}

<div class="text-center">
    <h1 class="display-4">@Model.Name</h1>
    
    @foreach (Room room in Model.Rooms)
    {
        <div class="room-item">
            <p>@room.Name</p>
            <p>£@(room.Price/100)</p>
            <p>@fromDate To @toDate</p>
            
            @if (User.Identity!.IsAuthenticated)
            {
                if (Context.Session.GetObject<Room>("PackageRoom")?.Id == room.Id)
                {
                    <i class="bi bi-bag-check"></i>
                }
                using (Html.BeginForm("AddRoomToPackage", "Auth", FormMethod.Post))
                {
                    <input type="hidden" name="fromDate" value="@fromDate"/>
                    <input type="hidden" name="toDate" value="@toDate"/>
                    <input type="hidden" name="roomId" value="@room.Id"/>
                    <input type="submit" class="btn btn-primary" value="Add To Package"/>
                }
            }
        </div>
    }
</div>

TourOperator/Views/View/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To Pacific Tours!</h1>
</div>

TourOperator/Views/View/Tour.cshtml
@using TourOperator.Extensions
@using TourOperator.Models.Entities
@model TourOperator.Models.Entities.Tour

@{
    ViewData["Title"] = "Hotels";
    string fromDate = ViewBag.Message["fromDate"];
}

<div class="text-center">
    <h1 class="display-4">@Model.Name</h1>
    
    <div class="room-item">
        <p>@Model.Name</p>
        <p>£@(Model.Price/100)</p>
        <p>@fromDate (@Model.Length Days)</p>
        
        @if (User.Identity!.IsAuthenticated)
        {
            if (Context.Session.GetObject<Tour>("PackageTour")?.Id == Model.Id)
            {
                <i class="bi bi-bag-check"></i>
            }
            using (Html.BeginForm("AddTourToPackage", "Auth", FormMethod.Post))
            {
                <input type="hidden" name="fromDate" value="@fromDate"/>
                <input type="hidden" name="tourId" value="@Model.Id"/>
                <input type="submit" class="btn btn-primary" value="Add To Package"/>
            }
        }
    </div>
</div>

TourOperator/Views/View/TourSearch.cshtml
@using TourOperator.Extensions
@{
    ViewData["Title"] = "Tour Search";
    string dateNow = DateTime.Now.ToShortDate();
}

<div class="text-center">
    <h1 class="display-4">Hotel Search</h1>
    
    @using (Html.BeginForm("Tours", "View", FormMethod.Post))
    {
        <label for="from">From</label>
        <input type="date" name="from" id="from" class="form-control" value="@dateNow" min="@dateNow"/>

        <button type="submit" class="btn btn-primary">Submit</button>
    }
</div>